coverage:
  precision: 1
  round: down
  range: 85...95 # custom range of coverage colors from red -> yellow -> green
  status:
    project:
      default:
        # basic
        target: 90%
        threshold: 1%

codecov:
  require_ci_to_pass: true
