from parser.currency import Currency
from parser.currencyLookup import CurrencyLookup

currency_list = [
    Currency(name="TRXToken", unit="TRON", decimal_places=6,
             contract_address=""),
    Currency(name="GOLDCoinToken", unit="GOLD", decimal_places=6,
             contract_address="TQs33VBR68syFx93KQ9iYSg8Xyr68t3A3L"),
    Currency(name="SUNOLD", unit="SUNOLD", decimal_places=18,
             contract_address="TKkeiboTkxXKJpbmVFbv4a8ov5rAfRDMf9"),
    Currency(name="TigSwap", unit="Tig", decimal_places=18,
             contract_address="THRBFeEwKUoREVJCFpLm7JF4ph24bZAVDG"),
    Currency(name="JUST_Stablecoin", unit="USDJ", decimal_places=18,
             contract_address="TMwFHYXLJaRUPeW6421aqXL4ZEzPRFGkGT"),
    Currency(name="Tether_USD", unit="USDT", decimal_places=6,
             contract_address="TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"),
    Currency(name="JUST", unit="JST", decimal_places=18,
             contract_address="TCFLL5dx5ZJdKnWuesXxi1VPwjLVmWZZy9"),
    Currency(name="HODL", unit="HODL", decimal_places=18,
             contract_address="TW8epJzhhPZkCjadUQWWvHFfNi344EkNef"),
    Currency(name="Blockcola_Token", unit="COLA", decimal_places=6,
             contract_address="TSNWgunSeGUQqBKK4bM31iLw3bn9SBWWTG"),
    Currency(name="TAI", unit="TAI", decimal_places=18,
             contract_address="TRwS7apsNdRGzMBfhB2hVC4RhqfubUYZ8P"),
    Currency(name="PEARL", unit="PEARL", decimal_places=18,
             contract_address="TGbu32VEGpS4kDmjrmn5ZZJgUyHQiaweoq"),
    Currency(name="SUNSWAP-PEARL-TRX", unit="S-PEARL-TRX", decimal_places=6,
             contract_address="TAAMpPWJvMRnbkNuDNPTFyWcDUrvorqaaZ"),
    Currency(name="Tesla", unit="TSLA", decimal_places=18,
             contract_address="TBGWQXQjFysZiAevBakSb3NfLq2Tgc7A13"),
    Currency(name="matrlx", unit="TXN", decimal_places=18,
             contract_address="TGbt2sNbHb3Vjc6xnfvgXd52BrAMvkHQvG"),
    Currency(name="Kitchen", unit="KIT", decimal_places=18,
             contract_address="TGgUHkmotBAmxH1CQezdWeVcpYVLJSHLuU"),
    Currency(name="WHALES", unit="WHALES", decimal_places=6,
             contract_address="THQWi4gRDrmtCPqZArE8abuz8yjeaBZDFJ"),
    Currency(name="MoonPool.finance", unit="MFI", decimal_places=18,
             contract_address="TLuekEszx5fq61rPCLwga9c3RtAVyBc46j"),
    Currency(name="SUNSWAP-MFI-TRX", unit="S-MFI-TRX", decimal_places=6,
             contract_address="TLViGYtFaRQKB38DjBoHqJpDwaXqYSiqYS"),
    Currency(name="drink.finance", unit="drink", decimal_places=18,
             contract_address="TRnGyNhwAzEVJo5FN17bcYY6movhfNnnVK"),
    Currency(name="Draco", unit="DRACO", decimal_places=18,
             contract_address="TSnxjFfELL1CP9y1v3UmCh2FpcnUEvRiYE"),
    Currency(name="Cherry", unit="CHERRY", decimal_places=18,
             contract_address="TT6Zfdsxtwn97v5nD2Ewe6v6GAAXpRPP4h"),
    Currency(name="Turnip.land", unit="TNIP", decimal_places=18,
             contract_address="TTcUbUvask45Cq1o6XeDxavzxNUCzWZX5j"),
    Currency(name="SUNSWAP-TAI-TRX", unit="S-TAI-TRX", decimal_places=6,
             contract_address="TWJRYGpbRVVw7VEpxF51L8G3hpLaZ2wWaj"),
    Currency(name="BALL", unit="BALL", decimal_places=18,
             contract_address="TWWqNMyDTB3yhJ1bhz1Rwow1AVTfw46rqu"),
    Currency(name="Sriracha.io", unit="SRI", decimal_places=18,
             contract_address="TX4AHnTb3QHYuMZv6unzZSAQfCoj9pj1mn"),
    Currency(name="Salmon", unit="SAL", decimal_places=18,
             contract_address="TXyrq6xE49dJhBGBYRH4pZzq9QdXNKWUQa"),
    Currency(name="Dragon", unit="DRAGON", decimal_places=18,
             contract_address="TYLPtEvANesoVWEKKzbDFnfuiKdaRNkpmb"),
    Currency(name="star.finance", unit="STAR", decimal_places=18,
             contract_address="TYmc4Ucbd383NCt1g3GmUW6ChmrnBPLN9a"),
    Currency(name="SHARKS", unit="SHARKS", decimal_places=6,
             contract_address="TYuqZxxHjPdUT3WJz4pDGib5JJa2MFsE2h"),
    Currency(name="Carrot Finance", unit="CRT", decimal_places=18,
             contract_address="TZ7EvoZdEet2P9E2DKf9CtKf6EAyFwRAS3"),
    Currency(name="Dash Token", unit="DASH", decimal_places=6,
             contract_address="TJASWoyYgUw2M1jvDje7zYLooDCzWYRdkm"),
    Currency(name="Draco", unit="DRACO", decimal_places=18,
             contract_address="TYYCs9CDMbptKEJoCnmdv9zii4hZ6Ksu8A"),
    Currency(name="OOO", unit="OOO", decimal_places=18,
             contract_address="TRuKQpgNJAAogtGTMWZzUG6odMzu9aL9Cm"),
    Currency(name="RubyPool.finance", unit="RBY", decimal_places=18,
             contract_address="TRTdtP8pxuHfF6uS6jZkLrxtye2WnufDom"),
    Currency(name="Tronbox", unit="TBOX", decimal_places=6,
             contract_address="TSB3KYV2dSvafvDNnq82PWZeh4wP4FDhPK"),
    Currency(name="Peach", unit="PCH", decimal_places=18,
             contract_address="TYUcgKL812qEWFB1ZQ3j14xB3rPkLoSaS9"),
    Currency(name="KID", unit="KID", decimal_places=18,
             contract_address="TBDUswpeVJV6LzhfcDgaDZ4n7tFHkPzaYf"),
    Currency(name="ANB Finance", unit="ANB", decimal_places=10,
             contract_address="TDndaG9V79f3dVuVQHvGZjx3VWN9XxzGe9"),
    Currency(name="dick.finance", unit="DICK", decimal_places=18,
             contract_address="TG3qyUurwRAy5fZ6yKsBvasEyD3zQABu9c"),
    Currency(name="KEY", unit="KEY", decimal_places=18,
             contract_address="THTETc5BTyPsGyDZTDVko2qS9spa9hM2sw"),
    Currency(name="Galaxy", unit="GAL", decimal_places=18,
             contract_address="TK7FrxgwkKexzKKMwVXYeLMe9mEbqb5Jjn"),
    Currency(name="Bitcoin", unit="BTC", decimal_places=8,
             contract_address="TN3W4H6rK2ce4vX9YnFQHwKENnHjoxb3m9"),
    Currency(name="JackPool.finance", unit="JFI", decimal_places=18,
             contract_address="TN7zQd2oCCguSQykZ437tZzLEaGJ7EGyha"),
    Currency(name="bud.kid.finance", unit="BUD", decimal_places=18,
             contract_address="TVkwWZDpg2SPiUkHL3FdZtMTux3mipXR3P"),
    Currency(name="Apple", unit="APE", decimal_places=18,
             contract_address="TYZQ7RRhN6ph1RfP9iSNcz9GNHnrKH9ufG"),
    Currency(name="mytron.one", unit="mytron.one", decimal_places=6,
             contract_address="TJhBZCBa7bhEWDGPhAZ31eNwS8idKKFzz3"),
    Currency(name="Xing.finance", unit="XING", decimal_places=18,
             contract_address="TU9MBurGfTkugpWRDrmyQn6ajJ4Yip5EL5"),
    # Currency(name="foo", unit="bar", decimal_places=18,
    #          contract_address="baz"),

]

TronGrid_currency_lookup = CurrencyLookup.from_currency_list(currency_list)
