name: ci

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - '**.md'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install poetry
        uses: snok/install-poetry@v1.0.0
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Lint
        run: bash run-lint.sh

      - name: Load test resources
        run: bash run-load-resources.sh

      - name: Coverage
        run: bash run-test-ci.sh
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
